### PR TITLE
Added Ubuntu 16.04 at README.md

### PR DESCRIPTION
**Pull request by ptheofan**

### CODE REVIEW

**Comment by OlegKunitsyn** [comment]
undefined symbol: shout_init

**Comment by ptheofan** [comment]
which binary? 
Ubuntu or OSX?

**Comment by OlegKunitsyn** [comment]
Your story. Please take a look at the output of mvn install

**Comment by ptheofan** [comment]
did you run the `mv target/libshout-java.64.so target/libshout-java.so` ?
after story runs should have only libshout-java.so
Ubuntu 16.04 works with the 64bit version only. This error means you're using the 32bit version

**Comment by OlegKunitsyn** [comment]
Just installed fresh Ubuntu 15 64-bit. `mvn install` fails with `symbol lookup` error as described above. `mv target/libshout-java.64.so target/libshout-java.so` is the cheat which replaces new (broken?) libshout-java.so with libshout-java.64.so compiled by me on Debian system and attached to the repo. Not a solution, sorry.

**Comment by ptheofan** [comment]
I really find you very remarkable!
1. Both files are built on ubuntu for ubuntu (which btw Ubuntu is based on Debian)
2. You always bind to the non 64bit version (see your java code).
3. Ubuntu is 64bit - so, move (mv) the 64bit version over the 32bit version (aka replace).
4. Magic happens - you actually load the 64bit version (not named 64bit).
5. You can fix the binding (final static) in the java part for that, or people simply need to replace the 32bit file with the 64bit file.

obviously, there's something else wrong here... and you're gonna have to live with it.
Have a nice day.

**Comment by OlegKunitsyn** [comment]
Dear ptheofan, `mvn install` on Ubuntu 15 64bit creates `libshout-java.so` - the dynamically linked 64-bit ELF file. Please fork and be happy.
Cheers!

**Comment by sunil6525** [comment]
i am not able to use this library in my windows machine. Do this support windows or only in lnux machines? can you please help me out

**Comment by OlegKunitsyn** [comment]
[Answered](https://github.com/OlegKunitsyn/libshout-java/issues/2)

**Pull request closed without merging**
